-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZ9SY5uzWWBoh8G44
KCeFdU8IvHbXDeTZHDaIRQRyukigCgYIKoZIzj0DAQehRANCAASle/3ZXhoGoLJI
/INYbDgCqPq2ETE7aR6R5wX0tqKOS/vdhnZdFiRWSM6kQODOZhlvvSdMTmIj1COw
5e3/nZ/L
-----END PRIVATE KEY-----