// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAttyS8c3dT0eN0vNZXbbamtoqetIMcGp0',
    appId: '1:998511654081:web:71ec95cf37926676965040',
    messagingSenderId: '998511654081',
    projectId: 'dary-a74c8',
    authDomain: 'dary-a74c8.firebaseapp.com',
    storageBucket: 'dary-a74c8.firebasestorage.app',
    measurementId: 'G-3JEZ9L3TDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAttyS8c3dT0eN0vNZXbbamtoqetIMcGp0',
    appId: '1:998511654081:android:71ec95cf37926676965040',
    messagingSenderId: '998511654081',
    projectId: 'dary-a74c8',
    storageBucket: 'dary-a74c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttyS8c3dT0eN0vNZXbbamtoqetIMcGp0',
    appId: '1:998511654081:ios:71ec95cf37926676965040',
    messagingSenderId: '998511654081',
    projectId: 'dary-a74c8',
    storageBucket: 'dary-a74c8.firebasestorage.app',
    iosBundleId: 'com.example.dary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttyS8c3dT0eN0vNZXbbamtoqetIMcGp0',
    appId: '1:998511654081:ios:71ec95cf37926676965040',
    messagingSenderId: '998511654081',
    projectId: 'dary-a74c8',
    storageBucket: 'dary-a74c8.firebasestorage.app',
    iosBundleId: 'com.example.dary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAttyS8c3dT0eN0vNZXbbamtoqetIMcGp0',
    appId: '1:998511654081:web:71ec95cf37926676965040',
    messagingSenderId: '998511654081',
    projectId: 'dary-a74c8',
    authDomain: 'dary-a74c8.firebaseapp.com',
    storageBucket: 'dary-a74c8.firebasestorage.app',
  );
}